### ISSUE TITLE
Seems Launch via Parameters is not working anymore?

### ISSUE THREAD

**Issue by bpkdasbaum** [shupershuff/D2r-Multiboxing-Without-A-Script#1]
1. Browse to your Diablo 2 Resurrected game install folder (you only need one install folder).
2. Right click on d2r.exe and create shortcut. Copy shortcut to desktop.
3. Edit the shortcut and append the target field with:
-username YourBnetEmail -password YourBnetPassword -address <REGION>
* <REGION> could be us.actual.battle.net, EU.actual.battle.net or KR.actual.battle.net for Americas, Europe or Asia respectively.

Example:  "C:\Games\Diablo II Resurrected\D2R.exe" -username myemail@email.com -password greatpw12345 -address EU.actual.battle.net

--> Game will start but won't connect to battle.net, thus stay in "offline mode"

**Comment by shupershuff** [comment]
This method still works. Either you've typo'd your password or you have security verifications required on your account.

**Comment by bpkdasbaum** [comment]
I double checked my credentials, they are correct. I believe the issue is the authenticator / 2fa / MFA.
It will log me into "offline" selection. When I click click "online" it states "we couldn't verify your account with that information".

![image](https://github.com/shupershuff/D2r-Multiboxing-Without-A-Script/assets/122998380/5404ffb8-d05b-4a37-a188-7a1691de2aa8)

I assume this is happening because the game is missing the sign in token info.
I relogged on the website and in the battle.net client, there is no authenticator challenge. Additionally the token should be stored in my registry. But using just the D2R.exe won't log me in.

After about 10 more attempts I now get a captcha challenge and captcha.jpg file is dropped into my D2R folder, but it is not displayed in the game client, thus I can't solve it.

I relogged on the website and in the battle.net client, I verified the captchas there. When logging in via command line d2r.exe I am still dropped to offline mode.


Logging in via command line does work on my other account **without** authenticator / 2fa / MFA

**Comment by bpkdasbaum** [comment]
I went back to read the instructions, you do say:

> Drawback with this method is that Blizzard forgot to make this work with MFA, which is kind of moot anyway as Blizzard prevent you from using standard MFA apps (which allow additional accounts).


I didn't quite catch that. It's my bad, sorry for the trouble and thanks for checking it. 

If possible, please put this disclaimer in the beginning and maybe say something like "Does not work with blizzard authenticator / 2fa / MFA". This way it's more clear /visible :)
